name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # runs once a day
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Regaaan
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23F97316&color_dots=%23e8e8e8,%23fdba74,%23fb923c,%23f97316,%23c2410c
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23FDBA74&color_dots=%230d1117,%237c2d12,%23c2410c,%23f97316,%23fdba74

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
